### ISSUE TITLE
InvalidFunctionCall: Unexpected llvm intrinsic: 7> llvm.vector.reduce.or.v4i8

### ISSUE THREAD

**Issue by biggysmith** [KhronosGroup/SPIRV-LLVM-Translator#1631]
Hi,

I've been getting this error when translating some kernels:

```
InvalidFunctionCall: Unexpected llvm intrinsic:
7> llvm.vector.reduce.or.v4i8
```
Is this a supported function?

**Comment by MrSidims** [comment]
Hi, unfortunately there is no SPIR-V counterpart for this intrinsic to translate it appropriately. But still you can pass '--spirv-allow-unknown-intrinsics' option to the translator, in this case it will emit a regular function call in SPIR-V. In general it's not a good idea to add this option by default, since there is no guarantee the the device's SPIR-V consumer would support such intrinsic, but may it it would help in your case.

**Comment by Tengfei09** [comment]
@MrSidims Any updates about this intrinsic? I also got the same error when using LLVM-SPIRV.

**Comment by MrSidims** [comment]
Resolved by emulation of the intrinsic in https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2198
