### ISSUE TITLE
Manage SPIR-V headers as an external dependency

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/SPIRV-LLVM-Translator#210]
An old copy of (some of) the SPIR-V headers is currently committed under `lib/SPIRV/libSPIRV/{spirv.hpp,OpenCL.std.h}`.

Should the headers be managed as an external dependency, most likely a submodule, instead?

This would make it much easier to track header changes.

**Comment by neildhickey** [comment]
Agreed, there are some discrepancies between the upstream khronos headers and the ones committed, so that would need cleaning up too

**Comment by svenvh** [comment]
@AlexeySotkin @AlexeySachkov, llvm-spirv's copy of `spirv.hpp` has diverged from the official Khronos version (https://github.com/KhronosGroup/SPIRV-Headers/blob/master/include/spirv/unified1/spirv.hpp), in particular due to Intel-specific extensions it seems (e.g. `OpFunctionPointerINTEL`, `CapabilityFPGARegINTEL`, `DecorationMergeINTEL` etc).

It would be great if we could reduce this divergence again; do you have any plans to do so?

**Comment by AlexeySotkin** [comment]
I agree that the translator should use the official spir-v headers from the Khronos repository.
We do plan to upstream the Intel-specific extensions the spir-v headers repo. But I can't provide ETA for this activity. Meanwhile, I think we can move Intel-specific extensions into a separate header in this repo to unblock the switch.

Technically, I think we could manage the headers as a cmake external project - https://cmake.org/cmake/help/latest/module/ExternalProject.html

**Comment by AlexeySachkov** [comment]
@svenvh, we have actually started the activity of upstreaming our extensions into KhronosGroup/SPIRV-Headers, two PRs have been merged so far: KhronosGroup/SPIRV-Headers#150 and KhronosGroup/SPIRV-Headers#152

I honestly don't know what amount of work is left there, but @MrSidims should be able to answer that question

**Comment by MrSidims** [comment]
There are several other Intel extensions that mere committed since April 1st (on top of my previous upstreaming work, there is a discussion raised in https://github.com/KhronosGroup/SPIRV-Headers/issues/151, but it no longer a blocker).

To fully replace local spirv.hpp we need 4 things:
1. Upstream rest extensions;
2. Get rid of InternalLinkage type in the local copy, which is not a part of SPIR-V spec (I have started working on this, but didn't have much time to finish, the idea is to move it into spirv-internal.hpp);
3. Get rid of OpForward instruction (same);
4. Fix spelling of LoopControls (aka add 'Mask' postfix, that was my bad committing it with wrong spelling a time ago...).

**Comment by svenvh** [comment]
@AlexeySachkov @MrSidims great to see progress on this and thanks for the update!

> Get rid of InternalLinkage type in the local copy (see #460), which is not a part of SPIR-V spec (I have started working on this, but didn't have much time to finish, the idea is to move it into spirv-internal.hpp);

We might be able to help on this if needed, just let us know.

**Comment by AlexeySachkov** [comment]
> @AlexeySachkov @MrSidims great to see progress on this and thanks for the update!
> 
> > Get rid of InternalLinkage type in the local copy (see #460), which is not a part of SPIR-V spec (I have started working on this, but didn't have much time to finish, the idea is to move it into spirv-internal.hpp);
> 
> We might be able to help on this if needed, just let us know.

FYI: @MrSidims has posted a PR for that item: KhronosGroup/SPIRV-LLVM-Translator#573

**Comment by MrSidims** [comment]
Hi, a little update here with a following question.

1. LinkageTypeInternal and OpForward were moved to a separate header spirv_internal.hpp
2. All of Intel extensions are now on the way to SPIR-V Headers repository: 
https://github.com/KhronosGroup/SPIRV-Headers/pull/176
https://github.com/KhronosGroup/SPIRV-Headers/pull/177
(there are two more extensions, that are required to be upstreamed: SPV_INTEL_optimization_hints and SPV_INTEL_linkonce_odr, but there going to be replaced with KHR)
3. I have locally tested a fresh-new spirv.hpp generated locally - translator is buildable and LITs are passing, patch is here: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/810
4. Also there is a patch, that makes spirv.hpp downloadable from https://github.com/KhronosGroup/SPIRV-Headers : https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/813 (yet untested since the extension haven't yet landed).

But there is a question, that I want to address. There are some situations, when the extension isn't fully ready (it's public, but it's marked as preview or draft). Yet in these situations we want it be implemented in the translator (but may be we aren't ready to upstream to the SPIR-V Headers). There are several possible ways of doing this and I'd like to ask your opinions on how it can be done:
1. Move definitions for these extensions to spirv_internal.hpp
Pros:
- Everything is in place already;
- spirv.hpp is always matches with the official one
Cons:
- Doubling work on developer's side: one would need to revisit the implementation when the extension is published to remove these definitions from the internal header
2. Create a local .json file with a fork of buildSpvHeaders tool, so the tool could merge official spirv.core.grammar.json file with the local one and generate spirv.hpp during build time
Pros:
- No doubling work for developers;
Cons:
- In the end we will still have two different copies of spirv.hpp not on source level, but on build level (here I would ask @neildhickey how this option fits with the issue raised here: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/397#pullrequestreview-334580214 )
3. Commit preview extensions in https://github.com/KhronosGroup/SPIRV-Headers directly
Pros:
- Works as is;
Cons:
- I'm unsure how it fits in SPIR-V ideology. In theory, one could just mark the definitions with 'exclude' keyword.

Tagging @svenvh @kpet @neildhickey @johnkslang @AlexeySachkov @AlexeySotkin

**Comment by svenvh** [comment]
My personal preference order for the different options (from most favorite to least favorite) would be  3, 1, 2.

I see your concern for option 3 about whether it is fine for preview extensions to be committed early, but I can't give advice on that.  If option 3 isn't desirable, then option 1 sounds reasonably simple, as the work needed when an extension is published is to just remove the definitions from spirv_internal.hpp, if I understood correctly.  Option 2 sounds a bit over-complicated, especially when it involves forking an external tool and generating spirv.hpp at build time.

**Comment by svenvh** [comment]
Closing as #813 has landed.
