### ISSUE TITLE
Build failure with llvm 18.1.0

### ISSUE THREAD

**Issue by TimB87** [KhronosGroup/SPIRV-LLVM-Translator#2415]
Hey,

trying to update spirv-llvm-translator to v18.1.0 against the llvm 18.1.0 release from earlier today results in a build failure for me on x86_64 (on CRUX 3.7):
[spirv-llvm-translator.log](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/files/14515806/spirv-llvm-translator.log)

I did disable ccache as my setup invokes distcc and would distribute it to other hosts that have llvm 17 installed.
Our current spirv-headers and spirv-tools versions are vulkan-sdk-1.3.275.0.

**Comment by svenvh** [comment]
I believe you will need a more recent version of the SPIRV-Headers.

**Comment by TimB87** [comment]
There is no more recent release available though.

**Comment by svenvh** [comment]
Maybe @vmaksimo or @MrSidims can provide more detail, but I guess the backport #2388 introduced a dependency on SPIRV-Headers code that's not part of any official release yet?  I wonder if that's something we should try to avoid for releases (i.e., make sure that any SPIRV-Headers work that a SPIRV-LLVM-Translator release depends on is part of a SPIRV-Headers release).

**Comment by TimB87** [comment]
It would certainly be helpful for packagers :)

**Comment by MrSidims** [comment]
I vote to revert the backport while waiting for the official release, but would like to hear from @KorovinVlad and @vmaksimo

**Comment by MrSidims** [comment]
It also means that the patch must be reverted from other branches and may be we should consider checking out headers not from github headers repo, but loading a package. Though I must say, this will complicate some backpropagation of the features to intel graphics compiler, but guess it's our problem, not community's :)

**Comment by svenvh** [comment]
> may be we should consider on release branches of the translator to check out headers not from github headers repo, but loading a package

Yeah something like that, or only allow checking out tags (not raw SHA-1s) of the SPIRV-Headers on release branches.

**Comment by bashbaug** [comment]
Hi!  We discussed this issue (actually, https://github.com/KhronosGroup/SPIRV-Headers/issues/422) in our weekly SPIR-V teleconference.  In short, we are open to tagging the SPIR-V Headers more frequently, on a cadence suitable for the SPIR-V LLVM Translator.  The main things we would need to know are the tagging convention this project would like to use, which commits to tag, how frequently to tag, etc.

Another option to consider though is to pull headers from a specific "known good" commit ID.  This could be done via submodules (which I know can be controversial) or from something like the [SPIRV-Tools DEPS file](https://github.com/KhronosGroup/SPIRV-Tools/blob/main/DEPS).  Would this be easier, especially since the header requirements for this project update tend to update frequently?  Or, is having tags for dependencies much better for package maintainers?

**Comment by MrSidims** [comment]
Should be fixed now. @TimB87 do you still see the issue?

**Comment by TimB87** [comment]
@MrSidims Sorry, I haven't been able to build vulkan-validation-layers 1.3.280.0 successfully and wasn't yet able to check in detail why it fails. I'll give it another look later today and will report back.

**Comment by TimB87** [comment]
@MrSidims Can confirm that this works now :)
Thanks to everybody involved!

**Comment by daurnimator** [comment]
> Or, is having tags for dependencies much better for package maintainers?

Yes!
We package dependencies separately, so a git submodule is not of any use.

**Comment by jbeich** [comment]
Do you plan to revert the workarounds? For example, before #2434 llvm_release_180 branch had the same spirv-headers-tag.conf as llvm_release_190 after #2387. v19.1.0 requires vulkan-sdk-1.3.280 but v1[7-3].0.1 and v18.1.1 standardized on vulkan-sdk-1.3.275.0 (v1[7-3].0.0 and v18.1.0 each had different spirv-headers-tag.conf).
