### ISSUE TITLE
Support for clang 10

### ISSUE THREAD

**Issue by davidrohr** [KhronosGroup/SPIRV-LLVM-Translator#302]
The CMakeLists currently requires clang version 9.0.0, therefore it does not compile with the current clang master.

**Comment by svenvh** [comment]
We have a PR that fixes the build with current clang/llvm master: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/261

Unfortunately we cannot merge it yet as the llvm binaries on apt.llvm.org are out of date (and do not provide Clang/llvm 10 yet); merging it would break our Travis buildbot.

In the mean time, you can cherry-pick the changes from https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/261 locally in order to build with latest master.

**Comment by davidrohr** [comment]
thx
