### ISSUE TITLE
InvalidFunctionCall: Unexpected llvm intrinsic: llvm.ctlz.i32

### ISSUE THREAD

**Issue by davidrohr** [KhronosGroup/SPIRV-LLVM-Translator#303]
The attached test cails fails during spir-v translation with:
```
InvalidFunctionCall: Unexpected llvm intrinsic: llvm.ctlz.i32 [Src: /var/tmp/portage/dev-util/spirv-llvm-translator-9999/work/spirv-llvm-translator-9999/lib/SPIRV/SPIRVWriter.cpp:1485  ]
Stack dump:
0.      Program arguments: llvm-spirv test.bc 
1.      Running pass 'LLVMToSPIRV' on module 'test.bc'.
 #0 0x00007f7765b4af6a llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/lib/llvm/10/lib64/libLLVMSupport.so.10svn+0x188f6a)
 #1 0x00007f7765b48d64 llvm::sys::RunSignalHandlers() (/usr/lib/llvm/10/lib64/libLLVMSupport.so.10svn+0x186d64)
 #2 0x00007f7765b48ee5 (/usr/lib/llvm/10/lib64/libLLVMSupport.so.10svn+0x186ee5)
 #3 0x00007f77653350d0 (/lib64/libc.so.6+0x390d0)
 #4 0x00007f776533500b raise (/lib64/libc.so.6+0x3900b)
 #5 0x00007f776531e535 abort (/lib64/libc.so.6+0x22535)
 #6 0x00005606619d0d45 SPIRV::SPIRVErrorLog::checkError(bool, SPIRV::SPIRVErrorCode, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, char const*, unsigned int) (/usr/bin/llvm-spirv+0x1e3d45)
 #7 0x00005606619c4208 SPIRV::LLVMToSPIRV::transIntrinsicInst(llvm::IntrinsicInst*, SPIRV::SPIRVBasicBlock*) (/usr/bin/llvm-spirv+0x1d7208)
 #8 0x00005606619be37c SPIRV::LLVMToSPIRV::transValueWithoutDecoration(llvm::Value*, SPIRV::SPIRVBasicBlock*, bool) (/usr/bin/llvm-spirv+0x1d137c)
 #9 0x00005606619bfd9d (/usr/bin/llvm-spirv+0x1d2d9d)
#10 0x00005606619c713f SPIRV::LLVMToSPIRV::transFunction(llvm::Function*) (/usr/bin/llvm-spirv+0x1da13f)
#11 0x00005606619c7a2c SPIRV::LLVMToSPIRV::translate() (/usr/bin/llvm-spirv+0x1daa2c)
#12 0x00005606619c7be3 SPIRV::LLVMToSPIRV::runOnModule(llvm::Module&) (/usr/bin/llvm-spirv+0x1dabe3)
#13 0x00007f7765d56d8e llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/lib/llvm/10/lib64/libLLVMCore.so.10svn+0x1add8e)
#14 0x00005606619c7caf llvm::writeSpirv(llvm::Module*, SPIRV::TranslatorOpts const&, std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (/usr/bin/llvm-spirv+0x1dacaf)
#15 0x0000560661935e9e main (/usr/bin/llvm-spirv+0x148e9e)
#16 0x00007f776531fe5b __libc_start_main (/lib64/libc.so.6+0x23e5b)
#17 0x000056066193a19a _start (/usr/bin/llvm-spirv+0x14d19a)
```
I am compiling via:
```
clang++ -cl-std=clc++ -x cl -emit-llvm --target=spir64-unknown-unknown -cl-denorms-are-zero -cl-mad-enable -cl-no-signed-zeros -ferror-limit=1000 -Xclang -finclude-default-header -Dcl_clang_storage_class_specifiers -Wno-invalid-constexpr -c test.cl -o test.bc
llvm-spirv test.bc
```
with current clang/llvm master and SPIRV-LLVM_Translator master.

[test.tar.gz](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/files/3520295/test.tar.gz)

@AnastasiaStulova : I was trying to create a minimal example for my problem with the invalid cast, and in that process I came accross the problem of this bug report.

**Comment by AlexeySachkov** [comment]
Hi @davidrohr,

If I understand correctly, SPIR-V was mostly designed for graphic shaders and OpenCL kernels and hence doesn't have equivalents for each LLVM intrinsic. So, errors like this is pretty easy to face.

Briefly looking into the spec, I cannot find any suitable SPIR-V instruction except `popcount` from [OpenCL extended instruction set](https://www.khronos.org/registry/spir-v/specs/unified1/OpenCL.ExtendedInstructionSet.100.html). This instruction actually does the opposite thing, but we can emulate `ctlz` with it.

May I ask a few more questions? Just out of curiosity

Could you please tell a little bit more about your usage model of SPIR-V? I'm particularly interested in a source language and maybe SPIR-V extensions you are using (if any).

If your source language is different from OpenCL C, could you please leave some comments in #206? This issue is basically a discussion about having some "automagic" in the translator which allows to recognize which function in input file corresponds to which SPIR-V instruction or having some well-defined interface, so front-ends are able to say somehow which function in input file corresponding to which SPIR-V instruction.

I'm asking because right now most of the users of the translator (by my personal knowledge) are using it for OpenCL-related things and not for something else - it would be good to see additional feedback on this.

**Comment by svenvh** [comment]
I'm suspecting that the origin of the intrinsic is the use of `__builtin_clz(x)` in `GPUCommonMath::Clz`. Clang maps the builtin to the `llvm.ctlz` intrinsic.

@davidrohr, was there any reason to use the `__builtin` variant instead of the plain `clz` function? OpenCL has a `clz` builtin function, which the translator maps to `OpExtInst clz` from the OpenCL extended instruction set.

Supporting `llvm.ctlz` is probably something we should still be doing, as LLVM transformation passes may introduce calls to the intrinsic.

**Comment by davidrohr** [comment]
@AlexeySachkov : I am using SPIR-V for OpenCL from clang with -cl-std=clc++

**Comment by davidrohr** [comment]
@svenvh : There is no particular reason to use the `__builtin_clz`, this just came from porting the CPU version, where there is no `clz`, so I used the gcc / clang builtin.
I can change it to `clz` for the OpenCL version, no problem. In general, I think clang OpenCL / SPIR-V translation should be hand the builtin variant, also for other builtin functions.
