### ISSUE TITLE
Doesn't translate read/write_mem_fence

### ISSUE THREAD

**Issue by jekstrand** [KhronosGroup/SPIRV-LLVM-Translator#920]
The simpler `mem_fence()` built-in is properly translated to a SPIR-V **OpMemoryBarrier** but, as far as I can tell, the directional `read_mem_fence()` and `write_mem_fence()` aren't implemented.

**Comment by AlexeySachkov** [comment]
Hi @jekstrand, thanks for the report

Wow, I was surprised that such built-ins even exist. I guess that the reason they are not handled is because we don't have them in OpenCL CTS (KhronosGroup/OpenCL-CTS#668) and they are rarely (or better say never?) used in other OpenCL apps, but this is indeed a bug of the translator
